Repository riemann/riemann-tools, pull requests merged in 2022-09, with the labels that each got.

#241 Fix parsing of mdstat when device is being checked
  lib/riemann/tools/mdstat_parser.y
  spec/fixtures/mdstat/example-12
  spec/riemann/tools/mdstat_parser_spec.rb
Labels: bug

#243 Fix `riemann-haproxy` HTTP response processing
  lib/riemann/tools/haproxy.rb
Labels: bug

#242 Improve error reporting on parse error
  lib/riemann/tools/health.rb
  lib/riemann/tools/md.rb
  lib/riemann/tools/mdstat_parser.y
  lib/riemann/tools/uptime_parser.y
  lib/riemann/tools/utils.rb
  spec/riemann/tools/health_spec.rb
  spec/riemann/tools/md_spec.rb
Labels: enhancement

#244 Release 1.5.0
  CHANGELOG.md
  lib/riemann/tools/version.rb
Labels: skip-changelog

#245 Fix/Improve `riemann-md` mdstat parser
  lib/riemann/tools/mdstat_parser.y
  spec/fixtures/mdstat/example-13
  spec/riemann/tools/mdstat_parser_spec.rb
Labels: bug
